language: go
notificaitons:
  email:
    recipients: hugo@wetterberg.nu
    on_success: change
    on_failure: always
env:
  - GO111MODULE=on
install: true
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
